spring.application.name=chat-app-backend
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/chatapp?w=majority&journal=true}
spring.data.mongodb.auto-index-creation=true
server.error.include-message=always
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=20s
