server.error.include-message=never
server.error.include-stacktrace=never
server.error.include-binding-errors=never
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
spring.web.resources.cache.cachecontrol.max-age=1h
spring.web.resources.cache.cachecontrol.cache-public=true
